from openslides.utils.views import (TemplateView)#, AjaxView)
# from openslides.projector.api import get_active_slide
# from openslides.utils.tornado_webserver import ProjectorSocketHandler

class ClickerView(TemplateView):
    """
    View that captures keyboard events generated by a presentation
    remote
    """
    required_permissions = 'core.can_manage_projector'
    template_name = 'openslides_clicker/clicker_page.html'
